name: Deploy
on:
  push:
    tags: [ 'v*' ]

jobs:
  deploy:
    name: Deploy
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Deploy release
        run: ./gradlew publish --no-daemon --stacktrace
        env:
          ORG_GRADLE_PROJECT_paperUsername: ${{ secrets.DEPLOY_USER }}
          ORG_GRADLE_PROJECT_paperPassword: ${{ secrets.DEPLOY_PASS }}
